const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json({limit:'5mb'}));
app.use('/api/auth', require('./src/routes/auth.routes'));
app.use('/api/crimes', require('./src/routes/crime.routes'));
app.use('/api/alerts', require('./src/routes/alert.routes'));
app.use('/api/sos', require('./src/routes/sos.routes'));
app.get('/', (_,res)=>res.json({message:'Risk Radar API v2 running', docs:['/api/crimes/summary','/api/crimes/areas','/api/crimes/heatmap']}));
const PORT=process.env.PORT||5000; app.listen(PORT,()=>console.log(`Risk Radar backend running on ${PORT}`));
